nodeLinker: hoisted
autoInstallPeers: true
strictPeerDependencies: false
packageManagerStrict: false
allowBuilds:
    esbuild: true
    sharp: true
    "@tailwindcss/oxide": true
    unrs-resolver: true
    "@swc/core": true
