use_frameworks!
platform :ios, '13.0'

target 'CalcTimers' do
  # Tauri iOS runtime is provided by the `tauri ios init` CLI.
  # Run `pnpm tauri ios init` first, then `pod install` here.
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end
